// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLOnrV370DMjyqz406PJS924bsUYMZt1Q',
    appId: '1:706464015138:web:633f517b8d8cc48b83fb7b',
    messagingSenderId: '706464015138',
    projectId: 'water-detection-2',
    authDomain: 'water-detection-2.firebaseapp.com',
    storageBucket: 'water-detection-2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFA6p8gkJ3yWdU9sODFRQ9r44b5TZnooQ',
    appId: '1:706464015138:android:0653decc76b9765883fb7b',
    messagingSenderId: '706464015138',
    projectId: 'water-detection-2',
    storageBucket: 'water-detection-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxYGl3qhr-pc_jWiTA5J53RHYe-S_FrnA',
    appId: '1:706464015138:ios:d3d5a371d1cd765583fb7b',
    messagingSenderId: '706464015138',
    projectId: 'water-detection-2',
    storageBucket: 'water-detection-2.appspot.com',
    iosClientId: '706464015138-81clmkcdf9v6183j0j3sr8mfgqvo5ktk.apps.googleusercontent.com',
    iosBundleId: 'com.example.waterdetection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxYGl3qhr-pc_jWiTA5J53RHYe-S_FrnA',
    appId: '1:706464015138:ios:d3d5a371d1cd765583fb7b',
    messagingSenderId: '706464015138',
    projectId: 'water-detection-2',
    storageBucket: 'water-detection-2.appspot.com',
    iosClientId: '706464015138-81clmkcdf9v6183j0j3sr8mfgqvo5ktk.apps.googleusercontent.com',
    iosBundleId: 'com.example.waterdetection',
  );
}
