// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBybXta-dFMDOM-hDdNYbFOpdMKAfI11bM',
    appId: '1:507590100946:web:aa939b9be91e06a41aea0b',
    messagingSenderId: '507590100946',
    projectId: 'pfeapp-830f3',
    authDomain: 'pfeapp-830f3.firebaseapp.com',
    databaseURL: 'https://pfeapp-830f3-default-rtdb.firebaseio.com',
    storageBucket: 'pfeapp-830f3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnDRaSDNz6kOTE_EKxzd0xAlvyYeNsqow',
    appId: '1:507590100946:android:40ac6b267429aa5a1aea0b',
    messagingSenderId: '507590100946',
    projectId: 'pfeapp-830f3',
    databaseURL: 'https://pfeapp-830f3-default-rtdb.firebaseio.com',
    storageBucket: 'pfeapp-830f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN77ws4LHqMBkZvjotULOln0iGdsxFBds',
    appId: '1:507590100946:ios:2443c93de3a515551aea0b',
    messagingSenderId: '507590100946',
    projectId: 'pfeapp-830f3',
    databaseURL: 'https://pfeapp-830f3-default-rtdb.firebaseio.com',
    storageBucket: 'pfeapp-830f3.appspot.com',
    iosClientId: '507590100946-7f5f4ibjoif4iurqcqn0k93ja9nm35of.apps.googleusercontent.com',
    iosBundleId: 'com.example.projj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBN77ws4LHqMBkZvjotULOln0iGdsxFBds',
    appId: '1:507590100946:ios:2443c93de3a515551aea0b',
    messagingSenderId: '507590100946',
    projectId: 'pfeapp-830f3',
    databaseURL: 'https://pfeapp-830f3-default-rtdb.firebaseio.com',
    storageBucket: 'pfeapp-830f3.appspot.com',
    iosClientId: '507590100946-7f5f4ibjoif4iurqcqn0k93ja9nm35of.apps.googleusercontent.com',
    iosBundleId: 'com.example.projj',
  );
}
